// Career Language Studio — assessment question banks and level metadata.
//
// SOURCING: every question below is ORIGINAL — written for this assessment,
// not copied from any textbook, past exam, or third-party question bank.
// Difficulty and scope per level are grounded in the official public level
// frameworks for each exam:
//   - Japanese (JLPT): "Summary of Linguistic Competence Required for Each
//     Level" — the official JLPT site, run by the Japan Foundation and Japan
//     Educational Exchanges and Services (JEES). https://www.jlpt.jp/e/about/levelsummary.html
//   - Korean (TOPIK): official level descriptions and score bands published
//     by NIIED (National Institute for International Education, under
//     Korea's Ministry of Education), which administers TOPIK.
//     https://www.topik.go.kr
// This assessment is independent and unofficial — see the disclaimer on
// assessment.html. It is not affiliated with, endorsed by, or a licensed
// administrator of either exam.

const ASSESSMENT_LEVELS = {
  Japanese: ["N5", "N4", "N3", "N2", "N1"],
  Korean: ["TOPIK 1", "TOPIK 2", "TOPIK 3", "TOPIK 4", "TOPIK 5", "TOPIK 6"]
};

const ASSESSMENT_PASS_THRESHOLD = 0.6;

// Official-source grounding for each level, shown on the assessment page so
// the curriculum basis is transparent rather than just asserted.
const ASSESSMENT_LEVEL_SCOPE = {
  Japanese: {
    "N5": "Official JLPT scope (jlpt.jp): read and understand typical expressions/sentences in hiragana, katakana, and basic kanji; understand short, slowly-spoken conversations on familiar daily topics.",
    "N4": "Official JLPT scope (jlpt.jp): read and understand passages on familiar daily topics written in basic vocabulary and kanji; comprehend daily conversations spoken slowly.",
    "N3": "Official JLPT scope (jlpt.jp): understand everyday written materials and grasp summary information, including slightly difficult texts with some assistance; follow coherent everyday conversations spoken at near-natural speed.",
    "N2": "Official JLPT scope (jlpt.jp): read materials on a variety of topics such as newspaper/magazine articles and commentaries and understand intent; comprehend coherent conversations and news reports spoken at nearly natural speed.",
    "N1": "Official JLPT scope (jlpt.jp): read writings with logical complexity or abstract content on a variety of topics and comprehend structure and content comprehensively; comprehend coherent conversations, news reports, and lectures at natural speed, including relationships and logical structure."
  },
  Korean: {
    "TOPIK 1": "Official TOPIK scope (NIIED, topik.go.kr): basic survival communication — self-introduction, purchasing, ordering — using roughly 800 basic vocabulary words and simple sentence construction.",
    "TOPIK 2": "Official TOPIK scope (NIIED, topik.go.kr): discussion of familiar everyday topics using roughly 1,500–2,000 vocabulary words, with awareness of formal/informal register.",
    "TOPIK 3": "Official TOPIK scope (NIIED, topik.go.kr): maintains social relationships and handles public/transactional interactions in Korean with correct, natural word usage.",
    "TOPIK 4": "Official TOPIK scope (NIIED, topik.go.kr): understands news articles, social issues, and abstract topics with accuracy; grasps common cultural references and idioms.",
    "TOPIK 5": "Official TOPIK scope (NIIED, topik.go.kr): high fluency for professional research or work; engages with specialized topics (e.g. politics, economics) and distinguishes formal/informal, spoken/written register.",
    "TOPIK 6": "Official TOPIK scope (NIIED, topik.go.kr): near-native fluency for professional and academic use; handles complex discourse and implicit meaning."
  }
};

const ASSESSMENT_QUESTION_BANK = {
  Japanese: [
    // ---------- N5 ----------
    { level:"N5", category:"Reading", difficulty:"beginner", curriculum_reference:"JLPT N5 official scope — everyday notices",
      q:"掲示板に「本日休業」と書いてあります。この意味は何ですか。",
      options:["Open only today","Closed today","Open 24 hours","New shop opening soon"], answer:1 },
    { level:"N5", category:"Reading", difficulty:"beginner", curriculum_reference:"JLPT N5 official scope — everyday notices",
      q:"「この店は土曜日と日曜日は休みです。」この文が正しいのはどれですか。",
      options:["The shop is open Monday–Friday","The shop is open only on weekends","The shop is closed every day","The shop is a new shop"], answer:0 },
    { level:"N5", category:"Reading", difficulty:"beginner", curriculum_reference:"JLPT N5 official scope — everyday notices",
      q:"「会社は九時に始まります。八時半に来てください。」何時に来ますか。",
      options:["8時30分","9時","8時","9時30分"], answer:0 },
    { level:"N5", category:"Grammar", difficulty:"beginner", curriculum_reference:"Minna no Nihongo I / JLPT N5 grammar scope",
      q:"きのう、友だち＿会いました。",
      options:["を","に","で","は"], answer:1 },
    { level:"N5", category:"Grammar", difficulty:"beginner", curriculum_reference:"Minna no Nihongo I / JLPT N5 grammar scope",
      q:"毎朝コーヒーを＿。",
      options:["飲みます","飲んで","飲んだ","飲もう"], answer:0 },
    { level:"N5", category:"Grammar", difficulty:"beginner", curriculum_reference:"Minna no Nihongo I / JLPT N5 grammar scope",
      q:"テーブルの上＿ペンがあります。",
      options:["に","を","で","へ"], answer:0 },
    { level:"N5", category:"Vocabulary", difficulty:"beginner", curriculum_reference:"JLPT N5 vocabulary scope",
      q:"「会議室」の意味は何ですか。",
      options:["Meeting room","Break room","Reception desk","Parking lot"], answer:0 },
    { level:"N5", category:"Vocabulary", difficulty:"beginner", curriculum_reference:"JLPT N5 vocabulary scope",
      q:"「休み」の意味は何ですか。",
      options:["Day off / rest","Meeting","Salary","Schedule"], answer:0 },
    { level:"N5", category:"Workplace Language", difficulty:"beginner", curriculum_reference:"JLPT N5 scope — polite workplace phrases",
      q:"同僚が「少々お待ちください。」と言いました。何を頼まれていますか。",
      options:["Wait a moment","Come here immediately","Leave the room","Call back later"], answer:0 },
    { level:"N5", category:"Workplace Language", difficulty:"beginner", curriculum_reference:"JLPT N5 scope — polite workplace phrases",
      q:"同僚が帰るときに「お先に失礼します。」と言いました。何を言っていますか。",
      options:["Excuse me for leaving before you (leaving work)","Good morning","Thank you very much","I'm sorry, I'm late"], answer:0 },

    // ---------- N4 ----------
    { level:"N4", category:"Reading", difficulty:"elementary", curriculum_reference:"Minna no Nihongo II / JLPT N4 scope",
      q:"メール：「明日の会議は10時から11時までです。場所は3階の会議室Aに変更になりました。」何が変わりましたか。",
      options:["The meeting time","The meeting room","The meeting was cancelled","The attendee list"], answer:1 },
    { level:"N4", category:"Reading", difficulty:"elementary", curriculum_reference:"Minna no Nihongo II / JLPT N4 scope",
      q:"「今日は雨ですから、傘を持って行ってください。」なぜ傘を持って行きますか。",
      options:["Because it's raining today","Because it's sunny","Because it's a holiday","Because the shop is closed"], answer:0 },
    { level:"N4", category:"Reading", difficulty:"elementary", curriculum_reference:"Minna no Nihongo II / JLPT N4 scope",
      q:"「会議室の予約は先着順です。早めにご予約ください。」この文の意味は何ですか。",
      options:["Meeting room reservations are first-come, first-served — reserve early","Meeting rooms are free to use anytime","Meeting rooms are closed today","Reservations are not allowed"], answer:0 },
    { level:"N4", category:"Grammar", difficulty:"elementary", curriculum_reference:"Minna no Nihongo II / JLPT N4 grammar scope",
      q:"この書類は今日中に＿なければなりません。",
      options:["提出し","提出する","提出して","提出した"], answer:0 },
    { level:"N4", category:"Grammar", difficulty:"elementary", curriculum_reference:"Minna no Nihongo II / JLPT N4 grammar scope",
      q:"この仕事はあしたまでに＿ください。",
      options:["終わらせて","終わる","終わった","終わろう"], answer:0 },
    { level:"N4", category:"Grammar", difficulty:"elementary", curriculum_reference:"Minna no Nihongo II / JLPT N4 grammar scope",
      q:"今、彼は日本語を＿。",
      options:["勉強しています","勉強します","勉強した","勉強しよう"], answer:0 },
    { level:"N4", category:"Vocabulary", difficulty:"elementary", curriculum_reference:"JLPT N4 vocabulary scope",
      q:"「締め切り」の意味は何ですか。",
      options:["Deadline","Discount","Reservation","Signature"], answer:0 },
    { level:"N4", category:"Vocabulary", difficulty:"elementary", curriculum_reference:"JLPT N4 vocabulary scope",
      q:"「予定」の意味は何ですか。",
      options:["Schedule / plan","Salary","Discount","Uniform"], answer:0 },
    { level:"N4", category:"Workplace Language", difficulty:"elementary", curriculum_reference:"JLPT N4 scope — workplace requests",
      q:"上司が「この件について確認していただけますか。」と言いました。何を頼まれていますか。",
      options:["A confirmation check on this matter","A refund request","A meeting cancellation","A day off"], answer:0 },
    { level:"N4", category:"Workplace Language", difficulty:"elementary", curriculum_reference:"JLPT N4 scope — workplace phrases",
      q:"同僚が仕事の後に「お疲れ様でした。」と言いました。これは主に何のために使われますか。",
      options:["A common phrase acknowledging someone's hard work, said when leaving or ending a task","An apology","A greeting used only in the morning","A request for help"], answer:0 },

    // ---------- N3 ----------
    { level:"N3", category:"Reading", difficulty:"intermediate", curriculum_reference:"JLPT N3 scope — workplace announcements",
      q:"「先週から新しいシステムを導入したため、一部の作業に時間がかかっています。ご不便をおかけしますが、ご理解のほどよろしくお願いいたします。」何を伝えていますか。",
      options:["A new system caused delays and apologizes for the inconvenience","The company is closing","A new employee has joined","A discount is being offered"], answer:0 },
    { level:"N3", category:"Reading", difficulty:"intermediate", curriculum_reference:"JLPT N3 scope — workplace announcements",
      q:"「本日、午後の会議は台風の影響で中止となりました。詳細は追ってご連絡いたします。」今日の午後の会議はどうなりましたか。",
      options:["It was cancelled due to a typhoon","It was moved to the morning","It was extended","It was made mandatory"], answer:0 },
    { level:"N3", category:"Reading", difficulty:"intermediate", curriculum_reference:"JLPT N3 scope — workplace announcements",
      q:"「新しい担当者が来月から加わる予定です。皆様どうぞよろしくお願いいたします。」この文は何を知らせていますか。",
      options:["A new team member is joining next month","A team member is leaving","The office is relocating","A holiday schedule change"], answer:0 },
    { level:"N3", category:"Grammar", difficulty:"intermediate", curriculum_reference:"JLPT N3 grammar scope",
      q:"資料を確認し＿、すぐにご連絡いたします。",
      options:["次第","ながら","ばかり","ついでに"], answer:0 },
    { level:"N3", category:"Grammar", difficulty:"intermediate", curriculum_reference:"JLPT N3 grammar scope",
      q:"雨が降っている＿、試合は行われた。",
      options:["にもかかわらず","ために","からには","というより"], answer:0 },
    { level:"N3", category:"Grammar", difficulty:"intermediate", curriculum_reference:"JLPT N3 grammar scope",
      q:"彼女は日本語＿、英語も話せる。",
      options:["ばかりでなく","にとって","にしては","のように"], answer:0 },
    { level:"N3", category:"Vocabulary", difficulty:"intermediate", curriculum_reference:"JLPT N3 vocabulary scope — business Japanese",
      q:"ビジネスの場面で「対応」に最も近い意味はどれですか。",
      options:["Handling / response to a matter","Vacation","Salary","Uniform"], answer:0 },
    { level:"N3", category:"Vocabulary", difficulty:"intermediate", curriculum_reference:"JLPT N3 vocabulary scope — business Japanese",
      q:"ビジネスの場面で「見直す」に最も近い意味はどれですか。",
      options:["To reconsider / review again","To celebrate","To delay indefinitely","To translate"], answer:0 },
    { level:"N3", category:"Workplace Language", difficulty:"intermediate", curriculum_reference:"JLPT N3 scope — client correspondence",
      q:"取引先からのメール：「恐れ入りますが、来週まで対応が難しい状況です。」何を伝えていますか。",
      options:["They can't accommodate the request until next week","They need the meeting today","They are cancelling the contract","They want a refund"], answer:0 },
    { level:"N3", category:"Workplace Language", difficulty:"intermediate", curriculum_reference:"JLPT N3 scope — internal correspondence",
      q:"同僚からのメール：「念のため、添付ファイルをご確認ください。」何を頼んでいますか。",
      options:["Please check the attached file, just to be safe","Please delete the file","Please forward this to everyone","Please ignore the attachment"], answer:0 },

    // ---------- N2 ----------
    { level:"N2", category:"Reading", difficulty:"upper-intermediate", curriculum_reference:"JLPT N2 scope — workplace trend articles",
      q:"「近年、リモートワークの普及に伴い、社員同士のコミュニケーション不足が課題として挙げられている。そのため、多くの企業がオンライン上での交流機会を増やす取り組みを始めている。」この文章の要点は何ですか。",
      options:["Companies are increasing online interaction to address communication gaps from remote work","Remote work is being banned","Employees are quitting because of remote work","Communication tools are too expensive"], answer:0 },
    { level:"N2", category:"Reading", difficulty:"upper-intermediate", curriculum_reference:"JLPT N2 scope — company announcements",
      q:"「当社は来年度より、全社員を対象とした語学研修制度を導入する予定です。」この会社は何を計画していますか。",
      options:["Introducing a language training program for all employees next fiscal year","Reducing employee salaries","Closing a branch office","Ending remote work"], answer:0 },
    { level:"N2", category:"Reading", difficulty:"upper-intermediate", curriculum_reference:"JLPT N2 scope — social/workplace commentary",
      q:"「近年、副業を認める企業が増えている一方で、労働時間管理の難しさも指摘されている。」この文章の要点は何ですか。",
      options:["More companies allow side jobs, but managing work hours has become harder","Side jobs are now illegal","Companies are reducing working hours","Employees are working less overall"], answer:0 },
    { level:"N2", category:"Grammar", difficulty:"upper-intermediate", curriculum_reference:"JLPT N2 grammar scope",
      q:"彼の説明を聞け＿聞くほど、分からなくなった。",
      options:["ば","と","のに","ながら"], answer:0 },
    { level:"N2", category:"Grammar", difficulty:"upper-intermediate", curriculum_reference:"JLPT N2 grammar scope",
      q:"彼は忙しい＿、手伝ってくれた。",
      options:["にもかかわらず","反面","上に","あまり"], answer:0 },
    { level:"N2", category:"Grammar", difficulty:"upper-intermediate", curriculum_reference:"JLPT N2 grammar scope",
      q:"この問題は複雑である＿、慎重に対応する必要がある。",
      options:["だけに","につけ","もかまわず","ぬきで"], answer:0 },
    { level:"N2", category:"Vocabulary", difficulty:"upper-intermediate", curriculum_reference:"JLPT N2 vocabulary scope — business reports",
      q:"報告書の中の「見込み」に最も近い意味はどれですか。",
      options:["Prospect / expected outcome","Apology","Invoice","Attendance"], answer:0 },
    { level:"N2", category:"Vocabulary", difficulty:"upper-intermediate", curriculum_reference:"JLPT N2 vocabulary scope — business reports",
      q:"職場での「把握する」に最も近い意味はどれですか。",
      options:["To grasp / fully understand a situation","To ignore","To postpone","To translate"], answer:0 },
    { level:"N2", category:"Workplace Language", difficulty:"upper-intermediate", curriculum_reference:"JLPT N2 scope — formal email conventions",
      q:"正式なビジネスメールで、名前の前に書く結びの言葉として最も適切なのはどれですか。",
      options:["よろしくお願いいたします。","じゃあね。","早く返事してね。","バイバイ。"], answer:0 },
    { level:"N2", category:"Workplace Language", difficulty:"upper-intermediate", curriculum_reference:"JLPT N2 scope — business email conventions",
      q:"ビジネスメールで「取り急ぎ、ご連絡まで。」はどのような意味で使われますか。",
      options:["A brief, preliminary note sent quickly, with more details to follow","A final decision","An urgent complaint","A formal apology"], answer:0 },

    // ---------- N1 ----------
    { level:"N1", category:"Reading", difficulty:"advanced", curriculum_reference:"JLPT N1 scope — formal business correspondence",
      q:"「本件に関しましては、社内での検討を重ねた結果、貴社のご提案を前向きに検討させていただく運びとなりました。」何を伝えていますか。",
      options:["They are positively considering the proposal after internal review","They are rejecting the proposal","They need more time before responding at all","They are cancelling the contract"], answer:0 },
    { level:"N1", category:"Reading", difficulty:"advanced", curriculum_reference:"JLPT N1 scope — abstract social/economic commentary",
      q:"「少子高齢化が進む中、労働力不足は今後さらに深刻化することが予想され、企業は多様な人材の活用を迫られている。」この文章の要点は何ですか。",
      options:["As the population ages, labor shortages are expected to worsen, pressuring companies to utilize diverse talent","The population is increasing rapidly","Companies are reducing hiring entirely","Labor shortages have already been resolved"], answer:0 },
    { level:"N1", category:"Reading", difficulty:"advanced", curriculum_reference:"JLPT N1 scope — highly formal business correspondence",
      q:"「本提案の採否につきましては、今後の社内審議を踏まえ、改めてご報告申し上げる所存でございます。」何を伝えていますか。",
      options:["A decision on the proposal will be reported later, after further internal review","The proposal has already been approved","The proposal has been rejected outright","No further communication will be sent"], answer:0 },
    { level:"N1", category:"Grammar", difficulty:"advanced", curriculum_reference:"JLPT N1 grammar scope",
      q:"彼が努力した＿、プロジェクトは成功した。",
      options:["からこそ","にすぎない","ないまでも","ながらも"], answer:0 },
    { level:"N1", category:"Grammar", difficulty:"advanced", curriculum_reference:"JLPT N1 grammar scope",
      q:"彼の実力＿、この結果は当然だ。",
      options:["からすれば","にひきかえ","といえども","ならでは"], answer:0 },
    { level:"N1", category:"Grammar", difficulty:"advanced", curriculum_reference:"JLPT N1 grammar scope",
      q:"多少の困難があろう＿、計画は予定通り進める。",
      options:["と","なら","ので","から"], answer:0 },
    { level:"N1", category:"Vocabulary", difficulty:"advanced", curriculum_reference:"JLPT N1 vocabulary scope — formal business Japanese",
      q:"正式なビジネス文書で「ご査収」は主にどのような意味で使われますか。",
      options:["Please review and accept (the enclosed documents)","Please discard","Please forward","Please translate"], answer:0 },
    { level:"N1", category:"Vocabulary", difficulty:"advanced", curriculum_reference:"JLPT N1 vocabulary scope — formal business Japanese",
      q:"「遺憾に思う」は正式なビジネス表現として主に何を表しますか。",
      options:["Formal regret / disappointment about a matter","Strong approval","Casual agreement","Enthusiasm"], answer:0 },
    { level:"N1", category:"Workplace Language", difficulty:"advanced", curriculum_reference:"JLPT N1 scope — formal apology conventions",
      q:"正式な謝罪メールに「多大なご迷惑をおかけし、深くお詫び申し上げます。」とあります。この文の目的・トーンは何ですか。",
      options:["A sincere formal apology for significant inconvenience caused","A casual thank-you note","A promotional offer","A meeting invitation"], answer:0 },
    { level:"N1", category:"Workplace Language", difficulty:"advanced", curriculum_reference:"JLPT N1 scope — highly formal correspondence closings",
      q:"非常に丁寧なビジネス文書が「今後とも変わらぬご愛顧のほど、よろしくお願い申し上げます。」で締めくくられています。この文の目的・トーンは何ですか。",
      options:["A formal request for continued patronage/support going forward","A termination notice","A casual farewell","A complaint"], answer:0 }
  ],

  Korean: [
    // ---------- TOPIK 1 ----------
    { level:"TOPIK 1", category:"Reading", difficulty:"beginner", curriculum_reference:"TOPIK I official scope — everyday notices",
      q:"표지판에 '오늘 휴무'라고 쓰여 있습니다. 이것은 무슨 뜻입니까?",
      options:["Open today","Closed today","New store","Sale today"], answer:1 },
    { level:"TOPIK 1", category:"Reading", difficulty:"beginner", curriculum_reference:"TOPIK I official scope — everyday notices",
      q:"'이 가게는 토요일과 일요일에 쉽니다.' 이 가게는 언제 문을 엽니까?",
      options:["Monday–Friday","Saturday only","Sunday only","Every day"], answer:0 },
    { level:"TOPIK 1", category:"Reading", difficulty:"beginner", curriculum_reference:"TOPIK I official scope — everyday notices",
      q:"'회사는 아홉 시에 시작합니다. 여덟 시 반까지 오세요.' 몇 시에 와야 합니까?",
      options:["8:30","9:00","8:00","9:30"], answer:0 },
    { level:"TOPIK 1", category:"Grammar", difficulty:"beginner", curriculum_reference:"TOPIK I official grammar scope",
      q:"저는 학교___ 갑니다.",
      options:["이","을","에","은"], answer:2 },
    { level:"TOPIK 1", category:"Grammar", difficulty:"beginner", curriculum_reference:"TOPIK I official grammar scope",
      q:"저는 아침마다 커피를 ___.",
      options:["마셔요","마시고","마셨어요","마실까요"], answer:0 },
    { level:"TOPIK 1", category:"Grammar", difficulty:"beginner", curriculum_reference:"TOPIK I official grammar scope",
      q:"책상 위___ 책이 있어요.",
      options:["에","을","도","만"], answer:0 },
    { level:"TOPIK 1", category:"Vocabulary", difficulty:"beginner", curriculum_reference:"TOPIK I official vocabulary scope",
      q:"'회의실'의 뜻은 무엇입니까?",
      options:["Meeting room","Restroom","Cafeteria","Parking lot"], answer:0 },
    { level:"TOPIK 1", category:"Vocabulary", difficulty:"beginner", curriculum_reference:"TOPIK I official vocabulary scope",
      q:"'쉬는 날'의 뜻은 무엇입니까?",
      options:["Day off","Meeting","Salary","Schedule"], answer:0 },
    { level:"TOPIK 1", category:"Workplace Language", difficulty:"beginner", curriculum_reference:"TOPIK I scope — polite workplace phrases",
      q:"동료가 '잠시만 기다려 주세요.'라고 말했습니다. 무엇을 부탁하고 있습니까?",
      options:["Please wait a moment","Please leave now","Please call later","Please hurry"], answer:0 },
    { level:"TOPIK 1", category:"Workplace Language", difficulty:"beginner", curriculum_reference:"TOPIK I scope — polite workplace phrases",
      q:"동료가 퇴근할 때 '먼저 가보겠습니다.'라고 말했습니다. 무슨 뜻입니까?",
      options:["I'll head out first (leaving work before others)","Good morning","Thank you very much","I'm sorry I'm late"], answer:0 },

    // ---------- TOPIK 2 ----------
    { level:"TOPIK 2", category:"Reading", difficulty:"elementary", curriculum_reference:"TOPIK I scope — workplace email",
      q:"이메일: '내일 회의는 오전 10시에서 오후 1시로 변경되었습니다.' 무엇이 바뀌었습니까?",
      options:["The meeting time","The meeting room","The meeting was cancelled","The attendee list"], answer:0 },
    { level:"TOPIK 2", category:"Reading", difficulty:"elementary", curriculum_reference:"TOPIK I scope — everyday notices",
      q:"'오늘은 비가 오니까 우산을 가지고 가세요.' 왜 우산을 가지고 갑니까?",
      options:["Because it's raining today","Because it's sunny","Because it's a holiday","Because the shop is closed"], answer:0 },
    { level:"TOPIK 2", category:"Reading", difficulty:"elementary", curriculum_reference:"TOPIK I scope — workplace notices",
      q:"'회의실 예약은 선착순입니다. 미리 예약해 주세요.' 이 문장의 뜻은 무엇입니까?",
      options:["Meeting room reservations are first-come, first-served — reserve early","Meeting rooms are free anytime","Meeting rooms are closed today","Reservations are not allowed"], answer:0 },
    { level:"TOPIK 2", category:"Grammar", difficulty:"elementary", curriculum_reference:"TOPIK I grammar scope",
      q:"이 서류를 오늘 안에 제출___ 합니다.",
      options:["해야","하고","해서","했지만"], answer:0 },
    { level:"TOPIK 2", category:"Grammar", difficulty:"elementary", curriculum_reference:"TOPIK I grammar scope",
      q:"이 일은 내일까지 ___ 주세요.",
      options:["끝내","끝나","끝났","끝낼까"], answer:0 },
    { level:"TOPIK 2", category:"Grammar", difficulty:"elementary", curriculum_reference:"TOPIK I grammar scope",
      q:"지금 그는 한국어를 ___.",
      options:["공부하고 있어요","공부해요","공부했어요","공부할 거예요"], answer:0 },
    { level:"TOPIK 2", category:"Vocabulary", difficulty:"elementary", curriculum_reference:"TOPIK I vocabulary scope",
      q:"'마감일'의 뜻은 무엇입니까?",
      options:["Deadline","Discount","Reservation","Signature"], answer:0 },
    { level:"TOPIK 2", category:"Vocabulary", difficulty:"elementary", curriculum_reference:"TOPIK I vocabulary scope",
      q:"'일정'의 뜻은 무엇입니까?",
      options:["Schedule / plan","Salary","Discount","Uniform"], answer:0 },
    { level:"TOPIK 2", category:"Workplace Language", difficulty:"elementary", curriculum_reference:"TOPIK I scope — workplace requests",
      q:"상사가 '이 부분을 확인해 주시겠어요?'라고 말했습니다. 무엇을 부탁하고 있습니까?",
      options:["A confirmation check on this part","A refund request","A meeting cancellation","A day off request"], answer:0 },
    { level:"TOPIK 2", category:"Workplace Language", difficulty:"elementary", curriculum_reference:"TOPIK I scope — workplace phrases",
      q:"동료가 퇴근 후 '수고하셨습니다.'라고 말했습니다. 이것은 주로 어떤 뜻으로 쓰입니까?",
      options:["A common phrase acknowledging someone's hard work, said when leaving or finishing a task","An apology","A morning-only greeting","A request for help"], answer:0 },

    // ---------- TOPIK 3 ----------
    { level:"TOPIK 3", category:"Reading", difficulty:"intermediate", curriculum_reference:"TOPIK II scope — workplace announcements",
      q:"'지난주부터 새로운 시스템을 도입하면서 일부 업무가 지연되고 있습니다. 불편을 드려 죄송합니다.' 이 글의 주된 내용은 무엇입니까?",
      options:["A new system has caused delays and apologizes for the inconvenience","The company is closing","A new employee joined","A discount is being offered"], answer:0 },
    { level:"TOPIK 3", category:"Reading", difficulty:"intermediate", curriculum_reference:"TOPIK II scope — workplace announcements",
      q:"'오늘 오후 회의는 태풍의 영향으로 취소되었습니다. 자세한 내용은 추후 안내드리겠습니다.' 오늘 오후 회의는 어떻게 되었습니까?",
      options:["It was cancelled due to a typhoon","It was moved to the morning","It was extended","It was made mandatory"], answer:0 },
    { level:"TOPIK 3", category:"Reading", difficulty:"intermediate", curriculum_reference:"TOPIK II scope — workplace announcements",
      q:"'새로운 담당자가 다음 달부터 합류할 예정입니다. 잘 부탁드립니다.' 이 글은 무엇을 알리고 있습니까?",
      options:["A new team member is joining next month","A team member is leaving","The office is relocating","A holiday schedule change"], answer:0 },
    { level:"TOPIK 3", category:"Grammar", difficulty:"intermediate", curriculum_reference:"TOPIK II grammar scope",
      q:"자료를 확인하___ 바로 연락드리겠습니다.",
      options:["는 대로","지만","면서","거나"], answer:0 },
    { level:"TOPIK 3", category:"Grammar", difficulty:"intermediate", curriculum_reference:"TOPIK II grammar scope",
      q:"비가 오___ 경기는 진행되었다.",
      options:["는데도","기 때문에","는 김에","는 대신"], answer:0 },
    { level:"TOPIK 3", category:"Grammar", difficulty:"intermediate", curriculum_reference:"TOPIK II grammar scope",
      q:"그녀는 한국어___ 영어도 할 수 있다.",
      options:["뿐만 아니라","에 비해","에 따라","와 달리"], answer:0 },
    { level:"TOPIK 3", category:"Vocabulary", difficulty:"intermediate", curriculum_reference:"TOPIK II vocabulary scope — business Korean",
      q:"업무 상황에서 '대응'에 가장 가까운 의미는 무엇입니까?",
      options:["Response / handling of a matter","Vacation","Salary","Uniform"], answer:0 },
    { level:"TOPIK 3", category:"Vocabulary", difficulty:"intermediate", curriculum_reference:"TOPIK II vocabulary scope — business Korean",
      q:"업무 상황에서 '재검토하다'에 가장 가까운 의미는 무엇입니까?",
      options:["To reconsider / review again","To celebrate","To delay indefinitely","To translate"], answer:0 },
    { level:"TOPIK 3", category:"Workplace Language", difficulty:"intermediate", curriculum_reference:"TOPIK II scope — client correspondence",
      q:"거래처 메시지: '죄송하지만 다음 주까지는 대응이 어려울 것 같습니다.' 무엇을 전달하고 있습니까?",
      options:["They can't accommodate the request until next week","They need the meeting today","They are cancelling the contract","They want a refund"], answer:0 },
    { level:"TOPIK 3", category:"Workplace Language", difficulty:"intermediate", curriculum_reference:"TOPIK II scope — internal correspondence",
      q:"동료 메시지: '혹시 몰라서, 첨부 파일 확인 부탁드립니다.' 무엇을 부탁하고 있습니까?",
      options:["Please check the attached file, just to be safe","Please delete the file","Please forward this to everyone","Please ignore the attachment"], answer:0 },

    // ---------- TOPIK 4 ----------
    { level:"TOPIK 4", category:"Reading", difficulty:"upper-intermediate", curriculum_reference:"TOPIK II scope — workplace trend articles",
      q:"'최근 재택근무가 확산되면서 직원 간 소통 부족이 문제로 지적되고 있다. 이에 따라 많은 기업들이 온라인 교류 기회를 늘리는 방안을 추진하고 있다.' 이 글의 요점은 무엇입니까?",
      options:["Companies are increasing online interaction to address communication gaps from remote work","Remote work is being banned","Employees are quitting because of remote work","Online tools are too expensive"], answer:0 },
    { level:"TOPIK 4", category:"Reading", difficulty:"upper-intermediate", curriculum_reference:"TOPIK II scope — company announcements",
      q:"'당사는 내년도부터 전 직원을 대상으로 한 어학 연수 제도를 도입할 예정입니다.' 이 회사는 무엇을 계획하고 있습니까?",
      options:["Introducing a language training program for all employees next fiscal year","Reducing employee salaries","Closing a branch office","Ending remote work"], answer:0 },
    { level:"TOPIK 4", category:"Reading", difficulty:"upper-intermediate", curriculum_reference:"TOPIK II scope — social/workplace commentary",
      q:"'최근 부업을 허용하는 기업이 늘고 있는 반면, 근무 시간 관리의 어려움도 지적되고 있다.' 이 글의 요점은 무엇입니까?",
      options:["More companies allow side jobs, but managing work hours has become harder","Side jobs are now illegal","Companies are reducing working hours","Employees are working less overall"], answer:0 },
    { level:"TOPIK 4", category:"Grammar", difficulty:"upper-intermediate", curriculum_reference:"TOPIK II grammar scope",
      q:"설명을 들으___ 들을수록 더 헷갈렸다.",
      options:["면","자마자","는데도","길래"], answer:0 },
    { level:"TOPIK 4", category:"Grammar", difficulty:"upper-intermediate", curriculum_reference:"TOPIK II grammar scope",
      q:"그는 바쁘___ 도와주었다.",
      options:["ㄴ데도","는 대신","는 김에","기는커녕"], answer:0 },
    { level:"TOPIK 4", category:"Grammar", difficulty:"upper-intermediate", curriculum_reference:"TOPIK II grammar scope",
      q:"이 문제는 복잡하기___ 신중하게 대응해야 한다.",
      options:["만큼","치고","는 둥","다시피"], answer:0 },
    { level:"TOPIK 4", category:"Vocabulary", difficulty:"upper-intermediate", curriculum_reference:"TOPIK II vocabulary scope — business reports",
      q:"보고서에서 '전망'에 가장 가까운 의미는 무엇입니까?",
      options:["Prospect / outlook","Apology","Invoice","Attendance"], answer:0 },
    { level:"TOPIK 4", category:"Vocabulary", difficulty:"upper-intermediate", curriculum_reference:"TOPIK II vocabulary scope — business reports",
      q:"직장에서 '파악하다'에 가장 가까운 의미는 무엇입니까?",
      options:["To grasp / fully understand a situation","To ignore","To postpone","To translate"], answer:0 },
    { level:"TOPIK 4", category:"Workplace Language", difficulty:"upper-intermediate", curriculum_reference:"TOPIK II scope — formal email conventions",
      q:"정식 비즈니스 이메일에서 이름 앞에 쓰는 맺음말로 가장 적절한 것은 무엇입니까?",
      options:["감사합니다.","안녕~","빨리 답장해.","잘가."], answer:0 },
    { level:"TOPIK 4", category:"Workplace Language", difficulty:"upper-intermediate", curriculum_reference:"TOPIK II scope — business message conventions",
      q:"업무 메시지에서 '우선 급한 대로 연락드립니다.'는 주로 어떤 의미로 쓰입니까?",
      options:["A brief, preliminary note sent quickly, with more details to follow","A final decision","An urgent complaint","A formal apology"], answer:0 },

    // ---------- TOPIK 5 ----------
    { level:"TOPIK 5", category:"Reading", difficulty:"advanced", curriculum_reference:"TOPIK II scope — formal business correspondence",
      q:"'본 건에 관하여 사내 검토를 거친 결과, 귀사의 제안을 긍정적으로 검토하게 되었음을 알려드립니다.' 무엇을 전달하고 있습니까?",
      options:["They are positively considering the proposal after internal review","They are rejecting the proposal","They need much more time before any response","They are cancelling the contract"], answer:0 },
    { level:"TOPIK 5", category:"Reading", difficulty:"advanced", curriculum_reference:"TOPIK II scope — abstract social/economic commentary",
      q:"'저출산 고령화가 심화되는 가운데, 노동력 부족은 향후 더욱 심각해질 것으로 예상되어 기업은 다양한 인재 활용이 요구되고 있다.' 이 글의 요점은 무엇입니까?",
      options:["As the population ages, labor shortages are expected to worsen, pressuring companies to utilize diverse talent","The population is increasing rapidly","Companies are reducing hiring entirely","Labor shortages have already been resolved"], answer:0 },
    { level:"TOPIK 5", category:"Reading", difficulty:"advanced", curriculum_reference:"TOPIK II scope — formal business correspondence",
      q:"'본 제안의 채택 여부는 향후 사내 심의를 거쳐 별도로 보고드릴 예정입니다.' 무엇을 전달하고 있습니까?",
      options:["A decision on the proposal will be reported later, after further internal review","The proposal has already been approved","The proposal has been rejected outright","No further communication will be sent"], answer:0 },
    { level:"TOPIK 5", category:"Grammar", difficulty:"advanced", curriculum_reference:"TOPIK II grammar scope",
      q:"그가 노력했___, 프로젝트는 성공하지 못했을 것이다.",
      options:["기에","을지라도","다시피","는커녕"], answer:0 },
    { level:"TOPIK 5", category:"Grammar", difficulty:"advanced", curriculum_reference:"TOPIK II grammar scope",
      q:"그의 실력___ 이 결과는 당연하다.",
      options:["으로 보면","에 비해","는 반면","와 달리"], answer:0 },
    { level:"TOPIK 5", category:"Grammar", difficulty:"advanced", curriculum_reference:"TOPIK II grammar scope",
      q:"다소 어려움이 있___ 계획은 예정대로 진행한다.",
      options:["더라도","다면","으니까","길래"], answer:0 },
    { level:"TOPIK 5", category:"Vocabulary", difficulty:"advanced", curriculum_reference:"TOPIK II vocabulary scope — formal correspondence",
      q:"정식 문서에서 '검토 부탁드립니다'는 주로 어떤 의미로 쓰입니까?",
      options:["Please review (the enclosed matter)","Please discard it","Please forward it","Please translate it"], answer:0 },
    { level:"TOPIK 5", category:"Vocabulary", difficulty:"advanced", curriculum_reference:"TOPIK II vocabulary scope — formal business Korean",
      q:"'유감스럽다'는 정식 비즈니스 표현으로서 주로 무엇을 나타냅니까?",
      options:["Formal regret / disappointment about a matter","Strong approval","Casual agreement","Enthusiasm"], answer:0 },
    { level:"TOPIK 5", category:"Workplace Language", difficulty:"advanced", curriculum_reference:"TOPIK II scope — formal apology conventions",
      q:"정식 사과 이메일에 '큰 불편을 드려 진심으로 사과드립니다.'라고 쓰여 있습니다. 이 문장의 목적·어조는 무엇입니까?",
      options:["A sincere formal apology for significant inconvenience caused","A casual thank-you note","A promotional offer","A meeting invitation"], answer:0 },
    { level:"TOPIK 5", category:"Workplace Language", difficulty:"advanced", curriculum_reference:"TOPIK II scope — highly formal correspondence closings",
      q:"매우 정중한 비즈니스 문서가 '앞으로도 변함없는 성원 부탁드립니다.'로 마무리됩니다. 이 문장의 목적·어조는 무엇입니까?",
      options:["A formal request for continued support going forward","A termination notice","A casual farewell","A complaint"], answer:0 },

    // ---------- TOPIK 6 ----------
    { level:"TOPIK 6", category:"Reading", difficulty:"advanced", curriculum_reference:"TOPIK II scope — formal partnership correspondence",
      q:"'귀사와의 협력 관계가 장기적으로 상호 발전에 기여할 것이라 판단되어, 이번 제안을 적극 추진하고자 합니다.' 무엇을 전달하고 있습니까?",
      options:["They intend to actively pursue the proposal, judging it mutually beneficial long-term","They are ending the partnership","They need to cancel the proposal","They are requesting a discount"], answer:0 },
    { level:"TOPIK 6", category:"Reading", difficulty:"advanced", curriculum_reference:"TOPIK II scope — abstract policy commentary",
      q:"'고령화 사회 진입과 더불어 의료 및 복지 분야에 대한 정책적 지원이 한층 강화될 전망이다.' 이 글의 요점은 무엇입니까?",
      options:["As society ages, policy support for healthcare and welfare is expected to strengthen further","Healthcare funding is being cut","The aging trend is reversing","Welfare policies have been eliminated"], answer:0 },
    { level:"TOPIK 6", category:"Reading", difficulty:"advanced", curriculum_reference:"TOPIK II scope — highly formal business correspondence",
      q:"'귀사의 요청 사항에 대해 내부적으로 다각도로 검토하였으나, 현 시점에서는 수용이 어려운 것으로 결론지었습니다.' 무엇을 전달하고 있습니까?",
      options:["After thorough internal review, they concluded they cannot accommodate the request at this time","They fully approved the request","They need no further review","They are ending the business relationship entirely"], answer:0 },
    { level:"TOPIK 6", category:"Grammar", difficulty:"advanced", curriculum_reference:"TOPIK II grammar scope",
      q:"'경기 침체에도 불구하고 매출은 오히려 증가했다.'에서 '에도 불구하고'의 기능은 무엇입니까?",
      options:["despite / notwithstanding","because of","in order to","as soon as"], answer:0 },
    { level:"TOPIK 6", category:"Grammar", difficulty:"advanced", curriculum_reference:"TOPIK II grammar scope",
      q:"예산이 부족함___ 불구하고 프로젝트는 성공적으로 마무리되었다.",
      options:["에도","으로","이라","이나마"], answer:0 },
    { level:"TOPIK 6", category:"Grammar", difficulty:"advanced", curriculum_reference:"TOPIK II grammar scope",
      q:"그가 직접 나서지 ___, 문제는 해결되지 않았을 것이다.",
      options:["않았더라면","않았으므로","않았다가","않았던지"], answer:0 },
    { level:"TOPIK 6", category:"Vocabulary", difficulty:"advanced", curriculum_reference:"TOPIK II vocabulary scope — business proposals",
      q:"사업 제안서에서 '타당성'에 가장 가까운 의미는 무엇입니까?",
      options:["Feasibility / validity","Discount rate","Attendance","Salary"], answer:0 },
    { level:"TOPIK 6", category:"Vocabulary", difficulty:"advanced", curriculum_reference:"TOPIK II vocabulary scope — policy/business proposals",
      q:"정책·사업 제안서에서 '실효성'에 가장 가까운 의미는 무엇입니까?",
      options:["Practical effectiveness","Popularity","Cost","Duration"], answer:0 },
    { level:"TOPIK 6", category:"Workplace Language", difficulty:"advanced", curriculum_reference:"TOPIK II scope — indirect formal refusal",
      q:"한국 비즈니스 서신에서 정중하고 완곡한 거절 표현으로 가장 적절한 것은 무엇입니까?",
      options:["이번 제안은 검토 결과 진행이 어려울 것으로 판단됩니다.","싫어요.","안 돼요.","못해요."], answer:0 },
    { level:"TOPIK 6", category:"Workplace Language", difficulty:"advanced", curriculum_reference:"TOPIK II scope — highly formal correspondence closings",
      q:"한국 비즈니스 서신에서 매우 정중한 마무리 인사로 가장 적절한 것은 무엇입니까?",
      options:["귀사의 무궁한 발전을 기원합니다.","다음에 봐요.","연락 주세요, 알겠죠?","네네 알겠습니다."], answer:0 }
  ]
};

// Recommended-resource lookup used on the results screen. IDs must match anchor
// ids on resources.html so results can deep-link to the right card.
const ASSESSMENT_RESOURCE_MAP = {
  Japanese: {
    "N5": [{ id:"irodori", title:"Irodori Starter (Japan Foundation, free)" }, { id:"JPO02", title:"Minna no Nihongo Elementary 1 (official)" }],
    "N4": [{ id:"marugoto", title:"Marugoto Elementary (Japan Foundation, free)" }, { id:"JPO07", title:"Shin Kanzen Master JLPT N4 Grammar (official)" }],
    "N3": [{ id:"nhk-world-japanese", title:"NHK World-Japan — Learn Japanese (free)" }, { id:"JPO13", title:"2000 Essential Vocabulary for JLPT N3 (official)" }],
    "N2": [{ id:"nhk-world-japanese", title:"NHK World-Japan — Learn Japanese (free)" }, { id:"JPO17", title:"2500 Essential Vocabulary for JLPT N2 (official)" }],
    "N1": [{ id:"JPO20", title:"JLPT N1 Shin Nihongo 500 Mon (official)" }, { id:"nhk-world-japanese", title:"NHK World-Japan — Learn Japanese (free)" }],
    "Below N5": [{ id:"irodori", title:"Irodori Starter (Japan Foundation, free)" }, { id:"JPO02", title:"Minna no Nihongo Elementary 1 (official)" }]
  },
  Korean: {
    "TOPIK 1": [{ id:"king-sejong", title:"King Sejong Institute — beginner course (free)" }, { id:"KRO01", title:"Sejong Korean Textbook, revised (official)" }],
    "TOPIK 2": [{ id:"ttmik", title:"Talk To Me In Korean — free lessons" }, { id:"KRO02", title:"Sejong Korean Vocabulary and Grammar (official)" }],
    "TOPIK 3": [{ id:"topik-guide", title:"TOPIK Guide — free practice materials" }, { id:"KRO06", title:"Korean Grammar in Use: Beginning (official)" }],
    "TOPIK 4": [{ id:"topik-guide", title:"TOPIK Guide — free practice materials" }, { id:"KRO16", title:"Complete TOPIK with One Book by Frequency (official)" }],
    "TOPIK 5": [{ id:"KRO17", title:"TOPIK II PICK — Reading and Writing (official)" }, { id:"KRO14", title:"TOPIK II Pass Recipe (official)" }],
    "TOPIK 6": [{ id:"KRO18", title:"TOPIK II: Write Along (official)" }, { id:"KRO15", title:"COOL TOPIK — full skills (official)" }],
    "Below TOPIK 1": [{ id:"king-sejong", title:"King Sejong Institute — beginner course (free)" }, { id:"KRO01", title:"Sejong Korean Textbook, revised (official)" }]
  }
};
